# Generated by Django 5.2.4 on 2025-07-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MineLucas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criaturas',
            name='bioma_spawn',
        ),
    ]
