# Generated by Django 5.2.4 on 2025-07-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MineLucas_app', '0002_remove_criaturas_bioma_spawn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estruturas',
            name='bioma',
        ),
    ]
