# Generated by Django 5.2.4 on 2025-07-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineLucas_app', '0003_remove_estruturas_bioma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('biografia', models.TextField()),
                ('criador_conteudo', models.BooleanField()),
                ('canal', models.TextField()),
                ('skin', models.TextField()),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
