# Generated by Django 5.2.4 on 2025-07-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineLucas_app', '0004_jogadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('Jogador', 'Jogador')], default='Jogador', max_length=255),
        ),
    ]
