# Generated by Django 5.2.4 on 2025-07-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineLucas_app', '0005_alter_usuario_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('Jogador', 'Jogador'), ('Admin', 'Admin')], default='Jogador', max_length=255),
        ),
    ]
